workdir: "/rhome/naotok/bigdata/neurodegeneration/GEO_SRA/GSE140205/Shiba"
container: docker://naotokubota/shiba:latest
gtf: "/rhome/naotok/bigdata/genome_annotation/Mouse/Mus_musculus.GRCm38.102.gtf"
experiment_table: "/rhome/naotok/neurodegeneration/config/splicing/experiment_Shiba_GSE140205.tsv"
unannotated: true
minimum_anchor_length: 6
minimum_intron_length: 70
maximum_intron_length: 500000
strand: XS
only_psi: false
only_psi_group: false
fdr: 0.05
delta_psi: 0.1
reference_group: EDIT_REFERENCE_GROUP
alternative_group: EDIT_ALTERNATIVE_GROUP
minimum_reads: 10
individual_psi: true
ttest: true
excel: true
